### ISSUE TITLE
Remove (?) aria-live attr from button

### ISSUE THREAD

**Issue by samiare** [nonsponsored/component-lottie#1]
https://github.com/nonsponsored/component-lottie/blob/9b8665802623634e5fb1497187dc42a5d2bb2040/index.html#L165C4-L185C10

Using `aria-live` for the button labels causes issues on screenreaders because button label changes are read regardless of whether you're focussed on the button on or not. For example, if you load the page with VoiceOver on, scroll down, and wait for the animation to end, you hear "replay animation" when the animation ends with no context and nothing actionable focussed.

On projects I've worked on before, it's been enough to just update the label. (Most) screenreaders will announce the change if the button has focus.

**Comment by nonsponsored** [comment]
Yep, good catch.
